{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"kafka-exporter:9308\", topic=~\"(otel-metrics|otel-traces)\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"kafka-exporter:9308\",topic=~\"(otel-metrics|otel-traces)\"}) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'kafka-exporter:9308', topic=~\"(otel-metrics|otel-traces)\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'kafka-exporter:9308',topic=~\"(otel-metrics|otel-traces)\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}