receivers:
  otlp:
    protocols:
      grpc: { endpoint: 0.0.0.0:4317 }
      http: { endpoint: 0.0.0.0:4318 }

connectors:
  spanmetrics:
    histogram:
      unit: ms
      explicit:
        buckets: [5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s]
    dimensions:
      - name: http.request.method
      - name: http.response.status_code
      - name: http.route
      - name: url.path
    exemplars:
      enabled: false
    metrics_flush_interval: 10s
    namespace: traces.spanmetrics

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: false
    resource_to_telemetry_conversion:
      enabled: true
  debug:
    verbosity: basic

processors:
  batch: {}

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus]
