port: 4222
http_port: 8222

# server_name é definido via NATS_SERVER_NAME env var em cada réplica

jetstream {
  store_dir: /data/jetstream
}

cluster {
  name: poc-cluster
  port: 6222
  routes: [
    nats://nats1:6222
    nats://nats2:6222
    nats://nats3:6222
  ]
}
