kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: rollouts
networking:
  podSubnet: "10.30.0.0/16"
  serviceSubnet: "10.31.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30300
    hostPort: 31300
    protocol: TCP
  - containerPort: 30090
    hostPort: 31090
    protocol: TCP
  - containerPort: 30880
    hostPort: 31880
    protocol: TCP
- role: worker
