global:
  domain: argocd.local

configs:
  params:
    server.insecure: "true"

server:
  service:
    type: NodePort
    nodePort: 30880
    servicePortHttp: 80
    servicePortHttps: 443
  extraArgs:
  - --insecure

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false
